### ISSUE TITLE
FEATURE: Alarm Clock

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-Android#71]
Reinstitute an alarm clock feature to allow users to set a timer that will automatically turn on the live stream at a specified time. Users can set an alarm duration anywhere between 5 mins and 23hrs 59mins in 5 minute increments. The current iPhone app can be used as a functional reference for how the feature is designed and implemented, although iOS has a limitation that prevents 3rd party apps from setting off alarms when the app is running in the background. If this is possible on Android, we can remove the user alert instructing them to leave the app in the foreground.

## User Stories

- [x] In the Alarm Clock view, users can select a time to wake up and engage the alarm feature
- [x] When the alarm clock is engaged, the app should display the wake time and a button to cancel the alarm.
- [x] When the device time == current alarm’s wake time, the live stream begins playing 
- [x] When a user loads the Alarm Clock view, the orange circular time setter should start at the current time and default to an 8 hour duration 
- [x] App has Mixpanel events for Alarm Clock features 

Mixpanel Events to add:

* userSetAlarm (when alarm clock is armed)
* AlarmFired (when alarm goes off)
* Alarm Canceled (when user manually cancels alarm)

Link to download design specs: https://www.dropbox.com/s/qu33zcs5uizfszg/AlarmClockDesignSpecs.zip?dl=0

**Comment by bricker** [comment]
Hey @sdillingham can you send me the alarm clock and stopwatch icons for the menu? I can get similar ones from iconmonstr but it may as well match the iphone app if possible.

**Comment by bricker** [comment]
I'm using Android's built-in Time selector function for this for a consistent Android experience (also because it's way easier :smile: ). The Lollipop one looks nice and functions really well anyways. Earlier versions of the time selector are okay too.

I have a basic working implementation of this ready to go that we can being testing at any time. It would be great if we had some older phones to test with (KitKat or below) because this required a small amount of version forking in the code and I don't have an older version to test.

**Comment by bricker** [comment]
This is complete except for the icons needed.
