### ISSUE TITLE
Live Rewind: Research and estimate work around improving HLS support in exoplayer

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-Android#89]
The goal here would be to improve the reliability of seeking by:

* giving the app a better understanding of the datetime included in the playlist
* being able to read total playlist duration from the mediaplaylist object

The acceptance criteria for this issue would be:

1) a brief summary of the work involved
2) a rough estimate of the number of hours needed to complete this work

**Comment by bricker** [comment]
I'm going to give a conservative estimate of 30 hours to get a stable seek working on the livestream. 
There are a few things that I need to do:

1. Add support for the `EXT-X-PROGRAM-DATE-TIME` tag into exoplayer (I will fork the code for this change). This includes parsing the tag and then adding it into the playlist object in a way that it will be accessible to the KPCC app.
2. Update the seek code to use the date time attribute rather than hardcoded values (as it does now).

**Comment by bricker** [comment]
cc @sdillingham @vsinghkpcc

**Comment by sdillingham** [comment]
@bricker: sounds good! If we can keep it to 30 hours, @vsinghkpcc and I say go for it.

**Comment by sdillingham** [comment]
@bricker it would be helpful to get a better understanding of the Exoplayer changes that were added as part of https://github.com/SCPR/KPCC-Android/pull/92. The commits in that PR don't account for any changes that might have been made to that dependency. Is there someplace where we can see the forked code for that library? If you have time to walk us through the changes that would be great, too.

**Comment by bricker** [comment]
Sean, I did make some changes but didn't actually end up using any of those
changes. The latest build has a locally built version of Exoplayer embedded
but I will revert to the HLS fork that I used in the last release. I'm able
to use the duration reported by Exoplayer to manage the timeline without
having to hardcode or assume any values.

If there are concerns with this approach let me know. Exoplayer has good
support for Dash including DVR-style seeking built right in, so I wonder if
adding Dash support to StreamMachine would be a better/faster option than
spending the time to fully implement HLS seeking into Exoplayer.
